development:
  adapter: postgresql
  encoding: unicode
  #database: jdt_data
  database: labkit
  # database: check_from_first
  # database: test
  port: 5432
  username: root
  password: root
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  # database: jdt_school
  database: labkit
  # database: check_from_first
  # database: test
  port: 5432 
  username: root
  password: root
  host: localhost
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>

test:
  adapter: postgresql
  encoding: unicode
  # database: jdt_school
  database: labkit
  # database: check_from_first
  # database: test
  port: 5432 
  username: root
  password: root
  host: localhost
